language: python
python:
- 3.8.3
install:
- pip install -r requirements.txt
- pip install codacy-coverage
script:
- python -m unittest
deploy:
  provider: heroku
env:
  - TOKEN=Njg5MDc5MTUzODMxODM3NzE2.Xm9o-A.lArjSGRIcB7Gbj5mA3ryPXR1kwc
